### ISSUE TITLE
sids installation

### ISSUE THREAD

**Issue by jinxyu** [zerothi/sids#1]
Dear Nick,

As you suggested, I downloaded the package (0.4.8) via https://github.com/zerothi/sids/releases. To be honest, I am not able to install sids through pypi interface due to the restrictions applied by the supercomputer. When I tried to install sids using the following command manually,

> python setup.py install --prefix=$HOME/LOCAL_APPS/SIDS

the systems echoed a fatal error, something like 
"fatal: Not a git repository (or any of the parent directories): .git
/apps/python/2.7.6/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'test_suite'
  warnings.warn(msg)"

Your kind suggestions will be appreciated. Cheers!

Jin

**Comment by zerothi** [comment]
It shouldn't matter, the installation proceeds otherwise correct?
If so, you shouldn't worry and you can use sids.

**Comment by zerothi** [comment]
I have removed the erroneous error message. It should now install without problems.
Please re-open if you have any troubles.
