### ISSUE TITLE
ImportError: No module named sids

### ISSUE THREAD

**Issue by jinxyu** [zerothi/sids#2]
Dear Nick,

Many thanks for your response!

Although the system echoed the error message, it seemed that the installation proceeded all right. After the installation, two files, e.g. sgeom and sgrid, were generated in the /bin folder. When I ran either of these two bin files at the terminal, 

> sgrid

I got the following rror message,

  File "sgrid", line 15, in <module>
    import sids
ImportError: No module named sids

May I have your suggestions? Cheers!

Jin

**Comment by zerothi** [comment]
You must have the sids package in your PYTHONPATH, i.e. if you do:

    python setup.py install --prefix=~/SIDS_PATH

you must add this to your `.bashrc` or equivalent `.profile`:

    export PYTHONPATH=$HOME/SIDS_PATH/lib/python2.7/site-packages:$PYTHONPATH

to enable the sids package.

**Comment by jinxyu** [comment]
Hi Nick, many thanks! I will try again! Cheers!

Jin

**Comment by jinxyu** [comment]
Hi Nick,

Although running "sgrid -h" displays all possible arguments, I am still a bit confused on how to use these parameters. Would you mind send me an example or a more detailed explanation document? Cheers!

Jin

**Comment by zerothi** [comment]
Hi Jin,

I still need to finish the documentation for the executables.

However, here is a brief show of what you possibly need:

    sgrid TotalPotential.grid.nc tp.cube

this will convert the grid in the potential file to a cube called tp.cube.
However, this will not automatically attach a geometry (atomic species and coordinates). To accomplish this, you need to use the `-g` or `--geometry` flag.
The argument of that flag may be any kind of siesta format for coordinates, fdf, xyz, XV etc.
Hence you can do:

    sgrid -g RUN.fdf TotalPotential.grid.nc tp.cube

and the cube will also contain the corresponding atomic coordinates.

If you want the difference between two files, say TS=0V and TS=0.5V you can do this (assuming you are in the folder containing the grid file for TS=0.5V):

    sgrid -g RUN.fdf -d ../TSrun_0/TotalPotential.grid.nc TotalPotential.grid.nc diff.cube

which then contains the difference cube. If you are using this for different spins, say with Rho.grid.nc, you can perform these:

    sgrid -g RUN.fdf Rho.grid.nc[0] spin_up.cube
    sgrid -g RUN.fdf Rho.grid.nc[1] spin_down.cube

where the square bracket denotes the spin-index in the NetCDF file. :)
I think this should cover the most basic need for now?

**Comment by jinxyu** [comment]
Hi Nick, 

Many thanks for your kind instruction! I still encounter some difficulties.

When I ran the following command as you suggested,
> sgrid -g 1Ben_free_0d00V.fdf TotalPotential.grid.nc ppp.cube
the system show
 "
  File "/home/566/jxy566/LOCAL_APPS/Python-2.7.6/bin/sgrid", line 241, in <module>
    run()
  File "/home/566/jxy566/LOCAL_APPS/Python-2.7.6/bin/sgrid", line 168, in run
    args.func(args)
  File "/home/566/jxy566/LOCAL_APPS/Python-2.7.6/bin/sgrid", line 218, in grid_action
    g = sids.Grid.read(f, var, idx)
  File "/home/566/jxy566/LOCAL_APPS/Python-2.7.6/lib/python2.7/site-packages/sids/grid.py", line 424, in read
    return get_sile(sile).read_grid(*args,**kwargs)
  File "/home/566/jxy566/LOCAL_APPS/Python-2.7.6/lib/python2.7/site-packages/sids/io/siesta_grid.py", line 42, in read_grid
    with self:
  File "/home/566/jxy566/LOCAL_APPS/Python-2.7.6/lib/python2.7/site-packages/sids/io/sile.py", line 237, in __enter__
    import netCDF4
ImportError: No module named netCDF4
"
So I tried to load netCDF4.3.0 by using "module load netCDF 4.3.0" or write "export NETCDF_PREFIX=/apps/netcdf/4.3.0" in .bashrc. They don't fix the problem. Would you mind make your suggestions? Cheers!

Jin

**Comment by zerothi** [comment]
You need to install the python package netcdf4-python, check the
requirements on the sids front page :)

--

Kind regards Nick Papior

**Comment by jinxyu** [comment]
Hi Nick, many thanks!

Jin

**Comment by zerothi** [comment]
I have updated the documentation for a small brief discussion of the `sgrid` command, if you have any questions or suggestions to the documentation, please let me know :)

http://zerothi.github.io/sids/bizstyle/scripts/sgrid.html

**Comment by jinxyu** [comment]
Dear Nick, many thanks!

Jin
